baseURL = 'https://poster.yojnaportal.com/'
languageCode = 'en-US'
title = 'YOJNA PORTAL POSTER'
theme = "postertheme"
enableGitInfo = true
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
[sitemap]
  changefreq = "daily"
  priority = 0.8
  filename = "sitemap.xml"
  [outputs]
  home = ["HTML", "JSON", "RSS"]

[params]
SiteDisclaimer = """
यह पोस्टर केवल सामान्य जानकारी प्रदान करने के उद्देश्य से बनाया गया है।  
हम यह सुनिश्चित नहीं करते कि ऊपर दी गई सभी जानकारी पूर्णतः सही, सटीक एवं समयानुसार अपडेट हो।  
संबंधित विभाग समय-समय पर अपनी आधिकारिक वेबसाइट पर जानकारी में बदलाव कर सकते हैं।  

यह वेबसाइट किसी भी सरकारी विभाग, बैंक, संस्था या संगठन की आधिकारिक वेबसाइट नहीं है।  
सभी योजनाओं, लोगो, नाम एवं ट्रेडमार्क का अधिकार उनके संबंधित विभागों एवं संस्थाओं के पास सुरक्षित है।  

किसी भी आवेदन, पंजीयन या सेवा का लाभ लेने से पहले संबंधित विभाग की आधिकारिक वेबसाइट या कार्यालय से जानकारी अवश्य सत्यापित करें।
"""